version: '3.9'

services:
  santex_db:
    container_name: santex_db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=santex
      - MYSQL_DATABASE=santex
    ports:
      - 3306:3306

  santex_app:
    container_name: santex_app
    image: santex-api-img:1.0.0
    build: .
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://santex_db:3306/santex?allowPublicKeyRetrieval=true
    ports:
      - 8080:8080
    depends_on:
      - santex_db

